config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  resources :articles

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :author
end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
	
	protected
	
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :name
		devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :find_article, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_author!, except: [:index, :show]

	def index
		@articles = Article.all.order("created_at DESC")
	end

	def show
		
	end

	def new
		@article = current_author.articles.build
	end

	def create
		@article = current_author.articles.build(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to root_path
	end

	private

	def find_article
		@article = Article.find(params[:id])
		
	end

	def article_params
		params.require(:article).permit(:title, :content, :bannerimage)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
	= f.input :title
	= f.input :content
	= f.input :bannerimage

	= f.button :submit

app/views/articles/edit.html.haml
%h1 Edit Article

= render 'form'

app/views/articles/index.html.haml
- @articles.each do |article|
	%h2= link_to article.title, article
	%p= article.content
	%p= article.bannerimage
	%p.username
		Shared by
		= article.author.name
		</br>about
		= time_ago_in_words(article.created_at)
		ago

app/views/articles/new.html.haml
%h1 Add New Article

= render 'form'

app/views/articles/show.html.haml
%h1= @article.title
%p= @article.content
%p= @article.bannerimage
%p.username
	Shared by
	= @article.author.name
	</br>about
	= time_ago_in_words(@article.created_at)
	ago 

= link_to "Edit", edit_article_path(@article)
= link_to "Destroy", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }

= link_to "Home", root_path

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Blog
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%header
		%nav
			- if author_signed_in?
				= link_to current_author.name, edit_author_registration_path
				= link_to "Add New Article", new_article_path
			-else
				= link_to "Sing In", new_author_session_path
				= link_to "Sing Up", new_author_registration_path

	%p.notice= notice
	%p.alert= alert

	= yield